 #Master node

vi rbac.yaml
kubectl apply -f rbac.yaml 
cat .kube/config
ls -lart .kube
kubectl describe secret devops-secret -n kube-system
kubectl describe secret developer-secret -n counterapp
cat .kube/config
kubectl get pods -n default
kubectl get pod

 #Worker node
 
 mkdir .kube
 vi .kube/config

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1UQXhNekV6TXpZeU9Wb1hEVE15TVRBeE1ERXpNell5T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTGlSCmt3V0loSjA4dlF0NE0rRHBRRTRyaEhCTFNpVElRTnp4eTI4ZXE1cDZwTk5yKzBiSENPMFRWM0Z0MmhKaEJFR2cKWFB0TkowdklNWFhFVGRlNW1uN1M0elBmK1hOWDg2Qy81NUg1UTFFcHowalVxNTQ3d2FrSHBtckdPRUxQOHIxcApRbllhS084ZnRXb2VpZXdobzNXZEo2c1RLRi9iaHhGUUZwWU5JdGo0TmFWcDFkY2tST2hVcXJpVXE2OFRqNVRhCkJ0VzRTTDBxbHl0UWxoVXJoQ1dHRVRkTXJUMzVXTmxlS3dKTDM5L0RaaXhPV3BKZjZTci8vMzZ4bm83K2ZYdG4KZFliYWhkWmM3VEFBTUJBbmkzTlg0UlVhRC9iQ21qLzRoVjBBeGpVUjlYbDB5VjQ5c3d3STVTNW1YSjA1TVhvTQp6bWpkU3JVZE5mVUxiYlZkdUhjQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCTlB2NzNjaVhZeFR3aDZQU2lFS2RMQTFFaU9NQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQkEwNnp6eXZ3RVVKSHlIc0k5QgpTbElkNGdCQ0JtZzBDdkFxamg0dFB1RzAycERxVGNEbEl4dHQ3Y2szaWhaRGJqa3N0ZVY1YndZYnkzSmltcGVaCmNZUGNUbk1tTUVHQ01KUVhqS1E3Q0V5Q1hDdTFsT2RNVjUzWnE2NVFUcnFtZlZqWjRuQWR1K2Z2NlFFVDNMTmIKUGZibDdFcmZKNVlSTHY0RURGZzhIYy8xS0k3L2s0KzZWTmljMjRIOGxzNExyUnJjU0hGR2tVSkQvWDhZaHQwcwpGYWJ6eGw5Y0ZBQWM3VTBGa1pkSktINEtndHdKemZmVU54OExKdzFXQjJqL0N3THJ1SUZISjBmdTZtd1E2WUFWCkpPTStNUWdkVzBzSWF4dllLZ3F5blRBcFZ0aUJCcUVuV2o1RjR0QkMvUkVkVjNZck5UaTRTT0RRM001aTR2T0kKRktNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://10.0.0.4:6443
  name: kubernetes


kind: Config
preferences: {}


#########################
#Worker node

kubectl config set-credentials devops --token=eyJhbGciOiJSUzI1NiIsImtpZCI6Ikd6WDZRdlUxcEZCOXhxaG5Ga0xzamRCYU10T29RN2FiVjIxMXI0UDJFRUkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZXZvcHMtc2VjcmV0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRldm9wcyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImM2MjA0M2NjLTE2YmYtNDhhYy1iODJmLTYxOWExNjViMzk3ZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpkZXZvcHMifQ.jKAGUtf0fXVprV6CLSrMH2N9xkvAs_vszp2zqJ1f9Lq8VVYEWOJV2njXcECutXwBEDWvrnbcxLd0EAQhzl_InFNe7bG33lDx_R6wiOVWjinfvsbH_bL1eDQDfquTL7xj1jduHkQ8chdrs2Gmdw7OYcrTo9NMejbuDEVgWpVi_m1YkOoRBg9_Joe4yLYA0g3KYBsRoDF3EvoJcq-2zTNwQ1zbs7MK80hJaHUzk7lHKR0Z005V2fNsjXS_LOWoIQa-zr72X0-IPGGCKbXu4YDfYyqBBN1DpodHWA_uBL7K3wCnio98isG68TR9A6w397ElZLsAY5kVgjlPSe-vL6GsCg

kubectl config set-credentials developer --token=eyJhbGciOiJSUzI1NiIsImtpZCI6Ikd6WDZRdlUxcEZCOXhxaG5Ga0xzamRCYU10T29RN2FiVjIxMXI0UDJFRUkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjb3VudGVyYXBwIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRldmVsb3Blci1zZWNyZXQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGV2ZWxvcGVyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMTc5MTY0OTktOWQyNi00ZDcyLThiM2ItMDc4NmQ2MTc5MTRlIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmNvdW50ZXJhcHA6ZGV2ZWxvcGVyIn0.jROlvHvK-Uf6_8qOdZQrQyABYSboiPAsSQGXHdAdi0IaqY_Wf648wFaB5prpX3JJQAz7UlWPpYSG_Ocfi-Rxfk_XHB3JG9MhHeNiVk8g6TRG8UrE0U6_FmVZYJrLDNlo69DeeLPuXSNeJzenBaT10KqP2YYQae7TBa47CgX04kxrwGnUtARx4d71f7OHhg5Z4inV1fCnyItoxmUzDPHYxhBNuYXvz6U69qFXZ2H3jZTLggVlOzN_h4WBMJhHsoT8XT_v8wmT7zt9YZlrwM9OEvLzKVCFHJ1W8BAWmwLbeia1b3rJ17s1a8cL896FOVMB5iu_y_Fzl4m3LHdnIJGtEg


#####kubectl get pods --kubeconfig myconfig

kubectl config set-context "developer@kubernetes" --cluster=kubernetes --user=developer

kubectl config set-context "devops@kubernetes" --cluster=kubernetes --user=devops

kubectl config use-context developer@kubernetes

kubectl config use-context devops@kubernetes
